name: Expo APK Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install dependencies
        run: |
          npm install -g eas-cli
          npm install --legacy-peer-deps
          
      - name: Build APK
        run: |
          eas build --platform android --non-interactive --output=./app.apk
        env:
          EXPO_TOKEN: ${{mevafGD223k18FCPjxD_4sfI3IpXr7N6xc4aZtPW}}
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: |
            app.apk
            metadata.json
